name: 'Connect to Twingate'
description: 'Connects to Twingate protected resources from your Github Action workflow'
branding:
  icon: 'arrow-right-circle'
  color: 'black'
inputs:
  service-key:
    description: 'Twingate Service Key'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Twingate (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        echo "deb [trusted=yes] https://packages.twingate.com/apt/ /" | sudo tee /etc/apt/sources.list.d/twingate.list
        sudo apt-get update -o Dir::Etc::sourcelist="sources.list.d/twingate.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
        sudo apt install -yq twingate
    - name: Setup and start Twingate (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        echo '${{ inputs.service-key }}' | sudo twingate setup --headless=-
        MAX_RETRIES=5
        WAIT_TIME=5
        n=0

        while [ $n -lt $MAX_RETRIES ]; do
          echo "Starting Twingate service..."
          sudo twingate start

          echo "Waiting $WAIT_TIME seconds for Twingate service to start..."
          sleep $WAIT_TIME

          status=$(sudo twingate status)

          if [ "$status" = "online" ]; then
            echo "Twingate service is connected."
            break
          else
            sudo twingate stop
          fi

          # Increment the retry counter and wait time
          n=$((n+1))
          WAIT_TIME=$((WAIT_TIME+5))

          echo "Twingate service is not connected. Retrying ..."
        done

        if [ $n -eq $MAX_RETRIES ]; then
          echo "Twingate service failed to connect."
          exit 1
        fi

    - name: Install and Start Twingate (Windows)
      if: runner.os == 'Windows'
      shell: powershell
      run: |
          Invoke-WebRequest https://api.twingate.com/download/windows?installer=msi -OutFile .\twingate_client.msi
          
          Set-Content .\key.json  '${{ inputs.service-key }}'
          $key_path = (Get-Item .\key.json | Resolve-Path).ProviderPath
          
          .\twingate_client.msi service_secret=$key_path /qn

          Start-Sleep -Seconds 30
          Get-Service twingate.service
          Start-Service twingate.service
          Start-Sleep -Seconds 10
          Get-Service twingate.service
