name: 'Connect to Twingate'
description: 'Connects to Twingate protected resources from your Github Action workflow'
branding:
  icon: 'arrow-right-circle'
  color: 'black'
inputs:
  service-key:
    description: 'Twingate Service Key'
    required: true
  debug:
    description: 'Enable debug output'
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Error if unsupported runner.os
      if: runner.os != 'Linux' && runner.os != 'Windows'
      shell: bash
      run: |
        echo "Unsupported Runner OS: ${{ runner.os }}"
        exit 1

    - name: Get latest Twingate version
      if: runner.os == 'Linux'
      id: twingate-version
      shell: bash
      run: |
        VERSION=$(curl -sf https://packages.twingate.com/apt/Packages | awk '/^Version:/ {print $2}' | sort -V | tail -1)
        if [ -z "$VERSION" ]; then
          echo "Failed to fetch version, proceeding without cache"
          echo "version=unknown" >> $GITHUB_OUTPUT
        else
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Latest Twingate version: $VERSION"
        fi

        # Get OS version for cache key
        OS_VERSION=$(grep VERSION_ID /etc/os-release | cut -d= -f2 | tr -d '"')
        echo "os_version=$OS_VERSION" >> $GITHUB_OUTPUT

    - name: Setup cache directory
      if: runner.os == 'Linux' && steps.twingate-version.outputs.version != 'unknown'
      shell: bash
      run: mkdir -p ~/.twingate-cache

    - name: Cache Twingate package and dependencies
      if: runner.os == 'Linux' && steps.twingate-version.outputs.version != 'unknown'
      uses: actions/cache@v5
      id: cache-twingate
      with:
        path: ~/.twingate-cache
        key: twingate-cache-v2-${{ runner.os }}-${{ runner.arch }}-${{ steps.twingate-version.outputs.os_version }}-v${{ steps.twingate-version.outputs.version }}

    - name: Validate cached package
      if: runner.os == 'Linux' && steps.cache-twingate.outputs.cache-hit == 'true'
      id: validate-cache
      shell: bash
      run: |
        DEB_FILE=$(ls ~/.twingate-cache/twingate*.deb 2>/dev/null | head -1)
        if [ -z "$DEB_FILE" ]; then
          echo "No .deb file found in cache"
          echo "valid=false" >> $GITHUB_OUTPUT
        elif ! dpkg-deb --info "$DEB_FILE" >/dev/null 2>&1; then
          echo "Cached .deb is corrupted"
          rm -rf ~/.twingate-cache/*
          echo "valid=false" >> $GITHUB_OUTPUT
        else
          echo "Cache is valid"
          echo "valid=true" >> $GITHUB_OUTPUT
        fi

    - name: Install Twingate from cache
      if: runner.os == 'Linux' && steps.validate-cache.outputs.valid == 'true'
      shell: bash
      run: |
        echo "Installing Twingate from cache"
        # Install all packages from cache directory (twingate + dependencies)
        sudo dpkg -i ~/.twingate-cache/*.deb || true
        sudo apt-get install -f -yq

    - name: Install Twingate (Linux)
      if: runner.os == 'Linux' && (steps.cache-twingate.outputs.cache-hit != 'true' || steps.validate-cache.outputs.valid != 'true' || steps.twingate-version.outputs.version == 'unknown')
      shell: bash
      run: |
        # Import Twingate GPG key for signature verification
        curl -fsSL https://packages.twingate.com/apt/gpg.key | sudo gpg --dearmor -o /usr/share/keyrings/twingate-client-keyring.gpg

        # Add Twingate repository with GPG key verification
        echo "deb [signed-by=/usr/share/keyrings/twingate-client-keyring.gpg] https://packages.twingate.com/apt/ * *" | sudo tee /etc/apt/sources.list.d/twingate.list

        sudo apt update
        sudo apt-get update -o Dir::Etc::sourcelist="sources.list.d/twingate.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"

        # Download all packages to cache if caching is enabled
        if [ "${{ steps.twingate-version.outputs.version }}" != "unknown" ]; then
          mkdir -p ~/.twingate-cache
          # Download Twingate and all dependencies to cache directory
          # Using sudo -E to preserve HOME and proper permissions
          sudo -E apt-get install -yq --download-only -o Dir::Cache::Archives="$HOME/.twingate-cache" twingate
          # Install to resolve any missing dependencies, then download them
          sudo -E apt-get install -yq --download-only -o Dir::Cache::Archives="$HOME/.twingate-cache" -f
          # Fix permissions so cache action can save files
          sudo chown -R $(id -u):$(id -g) ~/.twingate-cache
        fi

        sudo apt install -yq twingate
    
    - name: Setup and start Twingate (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        echo '${{ inputs.service-key }}' | sudo twingate setup --headless -
        MAX_RETRIES=5
        WAIT_TIME=5
        n=0

        while [ $n -lt $MAX_RETRIES ]; do
          echo "Starting Twingate service..."
          set +xe
          twingate start

          echo "Waiting $WAIT_TIME seconds for Twingate service to start..."
          sleep $WAIT_TIME

          status=$(twingate status)
          echo "Twingate service status: '$status'"

          if [ "$status" = "online" ]; then
            echo "Twingate service is connected."
            if [ "${{ inputs.debug }}" != "false" ]; then
              twingate resources
            fi
            break
          else
            twingate stop
            if [ "${{ inputs.debug }}" != "false" ]; then
              journalctl -u twingate --no-pager
            fi
          fi

          # Increment the retry counter and wait time
          n=$((n+1))
          WAIT_TIME=$((WAIT_TIME+5))

          echo "Twingate service is not connected. Retrying ..."
        done

        if [ $n -eq $MAX_RETRIES ]; then
          echo "Twingate service failed to connect."
          exit 1
        fi

    - name: Install and Start Twingate (Windows)
      if: runner.os == 'Windows'
      shell: powershell
      run: |
          Invoke-WebRequest https://api.twingate.com/download/windows?installer=msi -OutFile .\twingate_client.msi

          Set-Content .\key.json  '${{ inputs.service-key }}'
          $key_path = (Get-Item .\key.json | Resolve-Path).ProviderPath

          Start-Process msiexec.exe -Wait -ArgumentList "/i twingate_client.msi /l*v install.log log_level=debug service_secret=$key_path /quiet"

          Start-Sleep -Seconds 1
          Start-Service twingate.service

          Start-Sleep -Seconds 14
          Get-Service twingate.service